# Generated by Django 2.2.4 on 2020-01-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=200, null=True)),
                ('online', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('btsstatus', models.BooleanField(default=False)),
                ('hvacstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
