# Generated by Django 2.2.4 on 2020-02-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Powerapp', '0002_auto_20200205_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btsstatus', models.BooleanField(default=False)),
                ('hvacstatus', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('delta', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Powerapp.Module')),
            ],
        ),
    ]
