# Generated by Django 2.2.4 on 2020-03-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Powerapp', '0003_updatetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='genstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updatetracker',
            name='genstatus',
            field=models.BooleanField(default=False),
        ),
    ]
