# Generated by Django 2.2.4 on 2020-03-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Powerapp', '0004_auto_20200314_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatetracker',
            name='mainsstatus',
            field=models.BooleanField(default=False),
        ),
    ]
