# Generated by Django 2.2.4 on 2020-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Powerapp', '0005_updatetracker_mainsstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatetracker',
            name='genstatus',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='updatetracker',
            name='mainsstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
